version: '3'
services:
  app1:
    container_name: app1
    image: anatoly/rcsp5app
  app2:
    container_name: app2
    image: anatoly/rcsp5app
  app3:
    container_name: app3
    image: anatoly/rcsp5app
  app4:
    container_name: app4
    image: anatoly/rcsp5app
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
